#================================
# for tmux 2.9
#================================

# Unbind all key bingings
#unbind -a

# Replace prefix key (^b -> ^g)
unbind C-a
set -g prefix C-g
bind C-g send-prefix

# Reduce delay of keystroke
set -sg escape-time 2

# Set terminal
set -g default-terminal 'xterm'
set -g terminal-overrides 'xterm:colors=256'
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'
setw -g xterm-keys on

# Mouse
#set -g mode-mouse off
#set -g mouse-select-pane on
#set -g mouse-select-window on
#set -g mouse-resize-pane on

# Not Automatically set window title
setw -g automatic-rename off
set -g allow-rename off
#set -g window-status-format '#I:#(cmd="#{pane_current_command}"; echo ${cmd####*/})#F'
#set -g window-status-current-format '#I:#(cmd="#{pane_current_command}"; echo ${cmd####*/})#F'

set -g status-keys vi
set -g history-limit 50000
setw -g mode-keys vi

# Notification
# (legacy)
set -g visual-activity off
setw -g monitor-activity off
# (new)
# set -g visual-content off (obsoleted at 2.3)
# setw -g monitor-content 'complete' (obsoleted at 2.3)
set -g display-time 800

# Encoding and special character
# setw -g utf8 on (obsoleted at 2.3)
# set -g status-utf8 on (obsoleted at 2.3)
set -ga terminal-overrides ',*:jpacs@:enacs@:smacs@:rmacs:acsc@'

# Status and Tab bar
set -g set-titles on
set -g status-position top
set -g status-style bg=black
set -ag status-style fg=white
setw -g window-status-current-style bg=yellow
setw -ag window-status-current-style fg=black
setw -ag window-status-current-style bold
setw -g pane-active-border-style fg=green
setw -ag pane-active-border-style bg=black
set -g status-interval 10
set -g status-left-length 30
set -g status-left '#[fg=green](S:#S)'
set -g status-right '#[fg=yellow]#[default] #[fg=white]%H:%M#[default]'

# Session operations
bind -n M-d detach-client

bind -n M-T new-session
bind -n M-t choose-session
unbind s
#bind -n M-X kill-session

# Window operations
set -g base-index 1
set -g renumber-window on
bind -n M-Enter new-window -c "${HOME}"

bind -n M-n next-window
bind -n M-p previous-window

bind -n M-P swap-window -t :-
bind -n M-N swap-window -t :+

bind -n M-w kill-window

# Pane operations
setw -g pane-base-index 1
bind -n M-| split-window -h
bind -n M-- split-window -v

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L 3
bind -n M-J resize-pane -D 1
bind -n M-K resize-pane -U 1
bind -n M-L resize-pane -R 3

bind l join-pane -t :+ -v
bind h join-pane -t :- -v

bind -n M-f resize-pane -Z
bind -n M-Space swap-pane -D

bind -n M-q kill-pane

# Copy mode
bind -n M-[ copy-mode
bind -n M-] paste-buffer
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Utils bind
bind -n M-r run 'tmux source-file ~/.tmux.conf && tmux display-message "Reloaded config."'
bind -n M-: command-prompt
